// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"


const char THING_ID[] = "56fb1f4f-0e3b-47b0-89a3-ef7e082149ac";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTestChange();

float test;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(test, READWRITE, ON_CHANGE, onTestChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);